version: "3.9"
services:
  nginx:
    image: nginx:stable
    volumes:
      - ./:/app/:rw
    ports:
      - "80:80"
    networks:
      - load_balancer
    depends_on:
      - app_1

  app_1:
    image: app_1
    build:
      context: .
      dockerfile: Dockerfile
      target: app_1
    container_name: app_1
    ports:
      - "3000:3000"
    networks:
      - load_balancer
    
  app_2:
    image: app_2
    build:
      context: .
      dockerfile: Dockerfile
      target: app_2
    container_name: app_2
    ports:
      - "3001:3000"
    networks:
      - load_balancer

  # app_2:
  #   image: nginx:stable
  #   container_name: app_2
  #   tty: true
  #   volumes:
  #     - ./app:/app/:rw
  #   networks:
  #     - load_balancer

networks:
  load_balancer:
    driver: bridge
