version: "3.9"
services:
  nginx:
    image: nginx:stable
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:rw
    ports:
      - "80:80"
    networks:
      - load_balancer
    depends_on:
      - app_1

  app_1:
    container_name: app_1
    image: app_1
    build:
      context: .
      dockerfile: Dockerfile
      target: app_1
    networks:
      - load_balancer
    
  app_2:
    container_name: app_2
    image: app_2
    build:
      context: .
      dockerfile: Dockerfile
      target: app_2
    networks:
      - load_balancer

networks:
  load_balancer:
    driver: bridge
